### ISSUE TITLE
Shorter URLs

### ISSUE THREAD

**Issue by ghost** [nfrederick023/clipface#3]
Someone posted a Streamable link today and it reminded me of how short their URLs are. Is it possible to generate a 6-8 character long URL that redirects to the full URL without using third-party websites/services? Since you'd be redirecting to the long URLs, if you change your password not only would the original links fail to load anything now, so would the shorter URLs because they just redirect to the full URL.

I did find an open source service called [Kutt](https://github.com/thedevs-network/kutt) and they have an API you can generate keys for. Now, that isn't really self hosted because you're relying on them to redirect the URL for you, but that might be an easier way of doing it? I just thought there could be a way to enable/disable short URLs when you load the docker image and then if you enable it, every time you copy a URL, it would generate a 6-8 digit URL and then whenever Clipface sees someone using that short URL, it redirects them to the real one in a browser.

It just looks a lot cleaner in a chat.

**Comment by nfrederick023** [comment]
Thanks @snnacks for the suggestion.
I like your pitch, and think this would make for a great addition. 

I will be aiming to add this into the next release.

**Comment by nfrederick023** [comment]
Working on this feature. 
Branch feature/shortenedURLS

**Comment by nfrederick023** [comment]
Completed. Please see documentation for application state changes in regards to video IDs. 

Working on merge with master.

**Comment by ghost** [comment]
Awesome! I pulled that branch and it's working perfectly! Thank you.

**Comment by nfrederick023** [comment]
Finished #4
