### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by A1RB4SE** [nfrederick023/clipface#5]
The original clipface seems to be working fine after deploying but this one is returning following error.
`Application error: a client-side exception has occurred (see the browser console for more information).`

**Comment by ghost** [comment]
> The original clipface seems to be working fine after deploying but this one is returning following error. `Application error: a client-side exception has occurred (see the browser console for more information).`

The README was extremely outdated and included outdated Docker instructions. Please review the now up to date README.

**Comment by ghost** [comment]
Also, feel free to remove the previous docker image as well with the following command `docker image rm snnacks/better-clipface`. 

I am now going to close this issue, but before I do I would like to give a fair warning that this repository may soon be undergoing some major changes that involve adjusting the variable names one final time, etc. This means you will need to change them if you ever pull the update that contains the new variables. 

In the future the README will be updated as these changes are made.

**Comment by capaxed** [comment]
The issue still remains, as there is no such repo as nfrederick023/better-clipface, it's nfrederick023/clipface and the default password is not "unset" it is "test".

**Comment by ghost** [comment]
> The issue still remains, as there is no such repo as nfrederick023/better-clipface, it's nfrederick023/clipface and the default password is not "unset" it is "test".

[Here is a link to the docker hub repository nfrederick023/better-clipface.](https://hub.docker.com/r/nfrederick023/better-clipface)

As for the default password being "test", I just pushed an update to Docker Hub with the following changes:

- Changed default password to "adminadmin".
- Change default app path to "/data".
- Updated README with the above changes
- Added other custom variables to the README
